version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go-v2
    versions:
    - 1.2.1
    - 1.3.0
    - 1.3.1
    - 1.3.2
    - 1.3.3
    - 1.3.4
  - dependency-name: github.com/aws/aws-sdk-go-v2/config
    versions:
    - 1.1.5
    - 1.1.6
  - dependency-name: github.com/aws/aws-sdk-go-v2/service/sts
    versions:
    - 1.2.1
    - 1.2.2
    - 1.3.0
  - dependency-name: github.com/docker/docker
    versions:
    - 20.10.6+incompatible
  - dependency-name: github.com/aws/aws-sdk-go-v2/service/ecr
    versions:
    - 1.2.1
    - 1.2.2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
